[allow] local runs

diff --git a/run_stan b/run_stan
--- a/run_stan
+++ b/run_stan
@@ -7,11 +7,14 @@ ABSOLUTE_PATH="$(dirname $ABSOLUTE_PATH)"
 if [[ "$1" == "-h" || "$1" == "-help" || "$1" == "--help" ]]; then
     echo "Usage: ./run_stan OPTION1=value1 OPTION2=value2 ..."
     echo "OPTIONs:"
-    echo "    VL : viremic viral load threshold             [default: 1000]"
-    echo "    FTP: subset to first time participants or not [default: FALSE]"
-    echo "    STANWAY : either (r)stan or cmdstan           [default: cmdstan]"
-    echo "    ALPHA : sd for alpha prior in GP              [default: 1]"
-    echo "    SHARE : share hyperpars for FTP and ALL?      [default: TRUE]"
+    echo "    VL : viremic viral load threshold                                         [default: 1000]"
+    echo "    FTP: subset to first time participants or not                             [default: FALSE]"
+    echo "    STANWAY : either (r)stan or cmdstan                                       [default: cmdstan]"
+    echo "    ALPHA : sd for alpha prior in GP                                          [default: 1]"
+    echo "    SHARE : share hyperpars for FTP and ALL?                                  [default: TRUE]"
+    echo "    LOCAL : run the analysis locally?                                         [default: TRUE]"
+    echo "    MODELS : models to be run hyperpars (run-gp-{prevl,supp-pop,supp-hiv})    [default: ALL]"
+    echo "    ROUND : round                                                             [default: 19]"
     echo "    INDIR : directory where github directory is located"
     echo "    OUTDIR : directory where output will be saved"
     echo "    REFIT : if FALSE, will use previously fitted model, good for debugging "
@@ -37,6 +40,9 @@ REFIT="${FTP:-TRUE}"
 STANWAY="${STANWAY:-cmdstan}"
 INDIR="${INDIR:-$ABSOLUTE_PATH}"
 OUTDIR="${OUTDIR:-/rds/general/user/ab1820/home/projects/2022/longvl}"
+LOCAL="${LOCAL:-TRUE}"
+MODELS="${MODELS:-run-gp-prevl run-gp-supp-hiv run-gp-supp-pop}"
+ROUND="${ROUND:-19}"
 
 #################
 # OPTION CHECKS #
@@ -59,7 +65,7 @@ if [[ ! "$REFIT" =~ ^(TRUE|FALSE)$ ]]; then
 fi
 # stop if SHARE is not True, TRUE, T, False, FALSE, F
 if [[ ! "$SHARE" =~ ^(TRUE|FALSE)$ ]]; then
-    echo "SHARE must be either TRUE or FALSE."
+    echo "SHARE must be either TRUE or FALSE." 
     exit 1
 fi
 
@@ -72,6 +78,9 @@ echo "  STANWAY = $STANWAY"
 echo "  INDIR = $INDIR"
 echo "  OUTDIR = $OUTDIR"
 echo "  REFIT = $REFIT"
+echo "  LOCAL = $LOCAL"
+echo "  MODELS = $MODELS"
+echo "  ROUND = $ROUND"
 
 # "build" jobname and envname
 ENVNAME="longivl"
@@ -93,13 +102,9 @@ echo "  JOBNAME = $JOBNAME"
 # MAIN #
 ########
 
-mkdir $OUTDIR/$JOBNAME
+SUBMIT_CMD="qsub"
 
-MODELS="run-gp-prevl run-gp-supp-hiv run-gp-supp-pop"
-for MODEL in $MODELS
-do
-    cat > $OUTDIR/bash-$JOBNAME-$MODEL.pbs <<EOF
-#!/bin/sh
+HEAD="#!/bin/sh
 #PBS -l walltime=48:00:00
 #PBS -l select=1:ncpus=4:ompthreads=1:mem=99gb
 #PBS -J 16-19
@@ -113,16 +118,41 @@ set -euo pipefail
 
 JOB_TEMP=\${EPHEMERAL}/\${PBS_JOBID}
 mkdir -p \$JOB_TEMP
-cd \$JOB_TEMP 
+cd \$JOB_TEMP"
+
+
+HEAD2="#!/bin/sh
+#PBS -l walltime=24:00:00
+#PBS -l select=1:ncpus=4:ompthreads=1:mem=99gb
+#PBS -j oe
+#PBS -N l-$JOBNAME-$MODEL-postprocessing
+module load anaconda3/personal
+source activate $ENVNAME
+
+#  job will fail as soon as error occurs in your job script and that you don’t reference unset environment variables.
+set -euo pipefail"
+
+ROUND_CMD="ROUND=\\\$PBS_ARRAY_INDEX"
+
+if [[ "$LOCAL" == "TRUE" ]]; then
+    HEAD="#!/bin/sh
+    conda activate $ENVNAME"
+    HEAD2=$HEAD
+    ROUND_CMD="ROUND=$ROUND"
+    SUBMIT_CMD="sh"
+fi
+
+mkdir $OUTDIR/$JOBNAME
+for MODEL in $MODELS
+do
+    cat > $OUTDIR/bash-$JOBNAME-$MODEL.pbs <<EOF
+$HEAD
 PWD=\$(pwd)
 
 INDIR=$INDIR
 OUTDIR=$OUTDIR
 JOBNAME=$JOBNAME
-ROUND=\$PBS_ARRAY_INDEX
-
-# main directory
-# CWD=\$OUTDIR/\$JOBNAME/$MODEL
+$ROUND_CMD
 
 # mkdir -p \$CWD
 
@@ -157,7 +187,7 @@ cd \$OUTDIR
 
 if [ $(find $(pwd) -mindepth 1 -maxdepth 1 -type f -name "*rda" | wc -l) -eq 4 ]; then  
     echo "All models have finished running. Submitting postprocessing."
-    qsub bash-$JOBNAME-$MODEL-postprocessing.pbs
+    $SUBMIT_CMD bash-$JOBNAME-$MODEL-postprocessing.pbs
 else
     echo "Not all models have finished running. Not submitting postprocessing."
 fi
@@ -165,16 +195,7 @@ fi
 EOF
 
     cat > $OUTDIR/bash-$JOBNAME-$MODEL-postprocessing.pbs <<EOF
-#!/bin/sh
-#PBS -l walltime=24:00:00
-#PBS -l select=1:ncpus=4:ompthreads=1:mem=99gb
-#PBS -j oe
-#PBS -N l-$JOBNAME-$MODEL-postprocessing
-module load anaconda3/personal
-source activate longivl
-
-#  job will fail as soon as error occurs in your job script and that you don’t reference unset environment variables.
-set -euo pipefail
+$HEAD2
 
 INDIR=$INDIR
 OUTDIR=$OUTDIR
@@ -213,5 +234,5 @@ cd $OUTDIR
 
 for MODEL in $MODELS
 do
-    qsub bash-${JOBNAME}-${MODEL}.pbs
+    $SUBMIT_CMD bash-${JOBNAME}-${MODEL}.pbs
 done
